### ISSUE TITLE
polygonize na.rm=TRUE removes anywhere there is an NA

### ISSUE THREAD

**Issue by adrfantini** [mdsumner/spex#13]
`polygonize`'s `na.rm=TRUE` option sometimes removes some valid data from `rasterStack` objects, by assuming that all `NA`s are in the same place.
Imho it should only remove those polygons where **all** attributes are `NA`, not where **some** are. Example:

```R
library(raster)
library(spex)
library(sf)
fn <- system.file("external/test.grd", package="raster")
s <- stack(fn, fn)
s[[1]][50:60, 35:55] <- NA
polygonize(s, na.rm=TRUE)
```

Polygonize result:
![screenshot_20180423_115338](https://user-images.githubusercontent.com/12826141/39119778-02f7266c-46ed-11e8-84d9-ecd8bae76d1a.png)
Expected result (more in line with `plot(s)`)
![screenshot_20180423_115503](https://user-images.githubusercontent.com/12826141/39119834-2eb24624-46ed-11e8-98b5-c0e58d62087c.png)
:

**Comment by mdsumner** [comment]
Ok!   I'm having some problems with tests but I might push the change anyway, so you can see if it works. 

I had to remind myself why this is the way it is. Basically, the saving from na.rm = TRUE comes from quadmesh, which saves us from ever building the polygons in the first layer that are not NA.  I've made it now catch the case when not all NAs are common across layers, and then dropping any quads that aren't used. 

I'll see if quadmesh can be modified to use an input NA filter, because that could make it more efficient again.

**Comment by adrfantini** [comment]
It works as expected now, but non-`na-rm` polygonize seems to be borken:
```R
polygonize(s)
Error in `[[<-.data.frame`(`*tmp*`, "geometry", value = list(`550` = list( : 
  replacement has 2872 rows, data has 9200
```

**Comment by mdsumner** [comment]
Should be right now!  Thanks for the feedback, a good outcome - something I'd avoided dealing with properly until now. 

Do you think `na.rm` should be the default? I think it should, but might cause problems

**Comment by adrfantini** [comment]
Found a bug, apparently. Read in [this](https://drive.google.com/open?id=1Fi7nCulGi_6NfW-UjCYBhZ3W3vMhgB4o) example file:

```R
library(raster)
library(spex)
library(sf)
r = raster("euro4m_DJF.nc")
plot(r)
```
![](https://i.imgur.com/iiPYuIu.png)
Polygonize it:
```R
plot(polygonize(r))
```
![](https://i.imgur.com/ydxWhvv.png)

However if setting `na.rm=FALSE`:
```R
library(tidyr)
plot(polygonize(r, na.rm=FALSE) %>% drop_na())
```
![image](https://user-images.githubusercontent.com/12826141/40280016-5c533988-5c4d-11e8-803c-b66cb1ab443e.png)

So `na.rm=TRUE` has some problems. By the way, the documentation says it's `na.rm = FALSE` by default, but it seems the opposite.

**Comment by mdsumner** [comment]
I think I fixed this, but forgot to report back. 

I also found a nuance, when the raster has no values and na.rm = TRUE (now default) it was returning no polygons - but that was the entire point from the beginning, how easy it is to use raster to make a grid and then make polygons. Now fixed. 

If you are happy this should be right for a release soonish. Thanks!

**Comment by adrfantini** [comment]
Seems to work now! Happy to test more if necessary. Thanks.
