### ISSUE TITLE
polygonize: integer coordinates get a bit inaccurate

### ISSUE THREAD

**Issue by tobwen** [mdsumner/spex#18]
I've create an INSPIRE-compatible raster grid, which corner coordinate are integers. After using SPEX's polygonize, some of the corners got a bit inaccurate, like *394314.99999999* instead of *394315*.

Since st_precision() can't be directly applied to the geometry, I've just applied a small change to this function of *polygonize.RasterLayer* from

```
function(x) structure(list(matrix(x, ncol = 2)[c(1, 2, 3, 4, 1), ]), class = c("XY", "POLYGON", "sfg")))
```

```
function(x) structure(list(matrix(round(x, 0), ncol = 2)[c(1, 2, 3, 4, 1), ]), class = c("XY", "POLYGON", "sfg")))
```

I don't know if this is a problem of R, IEEE 754, sf or anything else. Perhaps anyone could have a look? The change of the function works for me, but might not be elegant.

**Comment by mdsumner** [comment]
Can you provide  a reprex (reproducible example)? I will take a look, but it might not be for a few weeks

**Comment by mdsumner** [comment]
fwiw I would rarely make polygons from rasters now, they just are so radically inefficient compared to a real mesh.  I would have pursued this if I had an example. I used to fudge the extent a bit in quadmesh (which you made me think of). 

But in that context now I do a more native interpolation of raster cells to corners here: 

https://github.com/hypertidy/anglr/blob/b26e2e56f4edd464d873624aae078b763fcd4991/R/utils.R#L182
