### ISSUE TITLE
vulnerability to PROJ6/GDAL3

### ISSUE THREAD

**Issue by rsbivand** [mdsumner/spex#22]
Running revdeps from sp (sp (my github fork) with development rgdal from R-Forge):

```
> packageVersion("sp")
[1] ‘1.3.4’
> packageVersion("rgdal")
[1] ‘1.5.3’
> rgdal::rgdal_extSoftVersion()
          GDAL GDAL_with_GEOS           PROJ             sp 
       "3.0.2"         "TRUE"        "6.2.1"        "1.3-2" 
```
a test fails:

```
> library(testthat)
> library(spex)
> 
> test_check("spex")
── 1. Failure: extent and crs works (@test-spex-extent.R#5)  ───────────────────
==... isn't true.

══ testthat results  ═══════════════════════════════════════════════════════════
[ OK: 35 | SKIPPED: 0 | WARNINGS: 16 | FAILED: 1 ]
1. Failure: extent and crs works (@test-spex-extent.R#5) 

Error: testthat unit tests failed
Execution halted
```

See:

http://rgdal.r-forge.r-project.org/articles/PROJ6_GDAL3.html
https://github.com/r-spatial/sf/issues/1231
https://github.com/r-spatial/sf/issues/1187
https://github.com/r-spatial/sf/issues/1146
https://github.com/r-spatial/discuss/issues/28

for background. See:

https://github.com/r-spatial/discuss/issues/28#issuecomment-551241421

for a way of testing fixes in a docker container contributed by Jakub Nowosad.

**Comment by mdsumner** [comment]
Thanks Roger. 

Small thing, any idea why `rgdal::rgdal_extSoftVersion()` returns 1.3.2 for sp rather than 1.3.4 as reported by `packageVersion`?  (It doesn't for me)

**Comment by mdsumner** [comment]
I don't think this has anything to do with new GDAL/PROJ, the projargs was logical NA and must be character.   (Strictly spex should hack its own way into the crs/wkt2 here and not rely on raster)

```R
#devtools::install_github("rsbivand/sp")
#devtools::install_github("rforge/rgdal/pkg")
packageVersion("sp") #[1] ‘1.3.4’
packageVersion("rgdal") #[1] ‘1.5.3’
rgdal::rgdal_extSoftVersion()
# GDAL GDAL_with_GEOS           PROJ             sp 
# "3.0.2"        "FALSE"        "6.2.1"        "1.3-4" 
```

**Comment by mdsumner** [comment]
I think the failing travis problem is due to new version of stringi (2020-01-09)

**Comment by mdsumner** [comment]
stringi fixed by not using trusty 94b24b9eae2f6b6946708e4102309bb48a919152

**Comment by rsbivand** [comment]
The underlying problem is that:

```
raster::projection(spex(raster::extent(lux), raster::projection(lux)))
# [1] "+proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs"
raster::projection(lux)
# [1] "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
```
so are not string-equal. Even `rgdal::compare_CRS()` - WIP - sees them as different.Unsure what to advise, maybe mute the test until things calm down. **rgdal** will be submitted to CRAN soon.

**Comment by mdsumner** [comment]
Eh, thanks sorry to miss that - I'll remove that pointless test

**Comment by mdsumner** [comment]
presumably was fixed by raster

**Comment by mdsumner** [comment]
I had thought rgdal was released already

**Comment by rsbivand** [comment]
I'm moving towards release, still a few revdep packages unresponsive.

**Comment by mdsumner** [comment]
I think we're good now, thanks!
